### ISSUE TITLE
3 monitors, 2 of same model, cant figure it out :/

### ISSUE THREAD

**Issue by Sincide** [ddmetz/ags-dots#1]
Hi, 
I'm trying to use your AGS dotfiles for my setup, it looks really good, but I have this problem that I have 3 monitors, 2 of them are the same model and I read in the main.js that it wont work if you have monitors of the same model, do you know how I can make it work so the bar doesnt show up twice on one othe monitors which are the same model?

![image](https://github.com/shezdy/ags-dots/assets/73416873/54cf0f62-60c6-49a4-850c-ab05e43678b0)

Thanks in advance :)

**Comment by shezdy** [comment]
try 91e089c52fd6521fda3be6968b286fc88b38d5ae. I updated it to use monitor position as the key instead of model.

**Comment by Sincide** [comment]
> try 91e089c52fd6521fda3be6968b286fc88b38d5ae. I updated it to use monitor position as the key instead of model.

I'll try that tomorrow, not at home right now, thank you 😊

**Comment by Sincide** [comment]
> try [91e089c](https://github.com/shezdy/ags-dots/commit/91e089c52fd6521fda3be6968b286fc88b38d5ae). I updated it to use monitor position as the key instead of model.

Thank you so much, that worked :)
